### ISSUE TITLE
Sustain GA Release 

### ISSUE THREAD

**Issue by labidiaymen** [labidiaymen/sustain#22]
### Support of all the REST functionalities support 

- [ ] Swagger/OpenApi support (extract metadata from function, class ...) https://github.com/labidiaymen/sustain/issues/14  

- [ ] Swagger UI extensions https://github.com/labidiaymen/sustain/issues/15

### Session extension

- [ ] Init, Read, Write from sessions https://github.com/labidiaymen/sustain/issues/16

- [ ] File provider for Session https://github.com/labidiaymen/sustain/issues/17

- [ ] Database provider for Session (MongoDB) https://github.com/labidiaymen/sustain/issues/18

### Basic extension/provider manager

- [ ] Import Export Apply Extensions/Modules https://github.com/labidiaymen/sustain/issues/20 

### Documentation  

- [ ] Full documentation of the mentioned features https://github.com/labidiaymen/sustain/issues/21
